export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_SUCCESS = 'FETCHING_SUCCESS';
export const FETCHING_FAILURE = 'FETCHING_FAILURE';

export const FETCHING_DATA_FILTER = 'FETCHING_DATA_FILTER';
export const FETCHING_SUCCESS_FILTER = 'FETCHING_SUCCESS_FILTER';
export const FETCHING_FAILURE_FILTER = 'FETCHING_FAILURE_FILTER';

export const FETCHING_DATA_UPDATE_COORDINATE = 'FETCHING_DATA_UPDATE_COORDINATE';
export const FETCHING_DATA_SUCCESS_COORDINATE = 'FETCHING_DATA_SUCCESS_COORDINATE';

export const FETCHING_SUGGESTING_DATA = 'FETCHING_SUGGESTING_DATA';
export const FETCHING_SUGGESTING_DATA_SUCCESS = 'FETCHING_SUGGESTING_DATA_SUCCESS';

export const FETCHING_DATA_INITIAL = 'FETCHING_DATA_INITIAL';
export const FETCHING_DATA_SUCCESS_INITIAL = 'FETCHING_DATA_SUCCESS_INITIAL';

export const FETCHING_DATA_SELECTED = 'FETCHING_DATA_SELECTED';
export const FETCHING_DATA_SUCCESS_SELECTED = 'FETCHING_DATA_SUCCESS_SELECTED';

export const FETCHING_DATA_SELECTEDID = 'FETCHING_DATA_SELECTEDID';
export const FETCHING_DATA_SUCCESS_SELECTEDID = 'FETCHING_DATA_SUCCESS_SELECTEDID';

export const UPDATED_DATA_BOUNDING = 'UPDATED_DATA_BOUNDING';
export const UPDATED_DATA_BOUNDING_SUCCESS = 'UPDATED_DATA_BOUNDING_SUCCESS';
